name: Deploy pres

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        spa: [DUW24_summary]  # List of SPAs to build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies and build
        run: |
          cd ${{ matrix.spa }}
          npm install @slidev/cli @slidev/theme-default slidev-theme-hep
          npm run build -- --base /${{ github.event.repository.name }}/${{ matrix.spa }}

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ matrix.spa }}/dist

      - name: List files after build
        run: |
          ls -R ${{ matrix.spa }}/dist


  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read    # to fetch code (actions/checkout)
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # strategy:
    #   matrix:
    #     spa: [DUW24_summary]  # List of SPAs to deploy 

    # # Deploy to the github-pages environment
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # with:
        #   artifact_name: ${{ matrix.spa }}/dist
